version: '3.8'

services:
  frontend:
    image: node:22
    container_name: todo_app_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173" # Frontend accessible at localhost:5173
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

  app:
    build: .
    container_name: todo_app_php
    ports:
      - "8080:80"   # PHP API at localhost:8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: todo_app
      DB_USER: root
      DB_PASS: rootpassword
    depends_on:
      - db
    #volumes:
     # - ./backend:/var/www/html  # PHP source

  db:
    image: mysql:8.0
    container_name: todo_app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d  # runs init.sql if present

volumes:
  db_data:
